SLIDES=intro.md
TEMPLATE=adaptTo2015_PresentationTemplate_trimmed.odp
OUTPUT=How_Do_I_Test_My_Sling_Application-Robert_Munteanu.odp

$(OUTPUT): $(SLIDES) $(TEMPLATE)
	odpdown --break-master=Topic_5f_v2 --content-master=Content_5f_v2 $(SLIDES) $(TEMPLATE) $(OUTPUT)

